// Problem 2: Even Fibonacci numbers
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms
// will be:
//   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.
;(() => {
  const want = 4613732
  let got = 0
  let prev = 0,
    next = 1
  while (next < 4000000) {
    if (next % 2 === 0) {
      got += next
    }
    let tmp = prev
    prev = next
    next = prev + tmp
  }
  console.log(`want(${want}) == got(${got}) = ${want === got}`)
})()
